### ISSUE TITLE
libopencv_java3.so not created when building opencv 3.4.2

### ISSUE THREAD

**Issue by louispetitjeanbfr** [Mainvooid/opencv-android-sdk-with-contrib#1]
Hi, first thanks a lot for your tutorial it was really great (even if i don't speak chinese !)
I tried to build opencv 3.4.2 with contrib, everything works great. But at the end of the build, the .so file wasn't created. Did I miss anything ?

**Comment by Mainvooid** [comment]
I recommend that you modify OPENCV_LIB_TYPE to STATIC in the Android. MK file to compile using static libraries. The resulting .so file size is smaller than libopencv_java3. so.
